# Generated by Django 5.2.7 on 2025-11-06 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='social_facebook',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='social_instagram',
        ),
        migrations.AddField(
            model_name='profile',
            name='social_discord',
            field=models.CharField(blank=True, max_length=100, verbose_name='Discord'),
        ),
        migrations.AddField(
            model_name='profile',
            name='social_telegram',
            field=models.CharField(blank=True, max_length=100, verbose_name='Telegram'),
        ),
    ]
