# Generated by Django 5.2.7 on 2025-11-06 20:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_postcomment_like_count_commentlike'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='like_count',
        ),
        migrations.AddField(
            model_name='post',
            name='vote_score',
            field=models.IntegerField(default=0, verbose_name='Рахунок голосів'),
        ),
        migrations.CreateModel(
            name='PostVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.SmallIntegerField(verbose_name='Значення')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='core.post', verbose_name='Пост')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Користувач')),
            ],
            options={
                'verbose_name': 'Голос за пост',
                'verbose_name_plural': 'Голоси за пости',
                'unique_together': {('post', 'user')},
            },
        ),
        migrations.DeleteModel(
            name='PostLike',
        ),
    ]
