# Generated by Django 5.2.7 on 2025-11-06 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_post_like_count_post_vote_score_postvote_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='video_url',
            field=models.URLField(blank=True, null=True, verbose_name='Посилання на відео (YouTube, etc.)'),
        ),
    ]
