# Generated by Django 5.2.7 on 2025-11-07 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_category_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='image',
        ),
    ]
