# Generated by Django 5.2.7 on 2025-11-25 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_post_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('published', 'Опублікована'), ('draft', 'Чернетка')], default='draft', max_length=10, verbose_name='Статус'),
        ),
    ]
