# Generated by Django 6.0.3 on 2026-06-08 19:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_category_slug_alter_post_slug_alter_tag_slug'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='subscribers',
            field=models.ManyToManyField(blank=True, related_name='subscribed_tags', to=settings.AUTH_USER_MODEL, verbose_name='Підписники'),
        ),
    ]
