"""
Django settings for dlango_blog project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Цей ключ потрібно згенерувати новий і заховати у змінну оточення
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', 'your-fallback-key-here')

# ВИМИКАЄМО РЕЖИМ ВІДЛАДКИ
DEBUG = True

# ВКАЗУЄМО ДОЗВОЛЕНІ ХОСТИ (адреси, з яких можна заходити на сайт)
ALLOWED_HOSTS = ['your_domain.com', 'www.your_domain.com', '127.0.0.1', 'localhost']

JAZZMIN_SETTINGS = {
    "site_title": "Мій Блог Admin",
    "site_header": "Мій Блог",
    "site_brand": "Панель Керування",
    "welcome_sign": "Ласкаво просимо! Увійдіть для керування блогом.",
    "favicon": "images/favicon.png",
    "search_model": ["users.CustomUser", "core.Post"],

    # Тема (використовуємо темну, як на вашому сайті)
    "theme": "darkly",

    # Налаштування UI
    "topmenu_links": [
        {"name": "Головна (Сайт)", "url": "core:home", "permissions": ["auth.view_user"]},
        {"model": "users.CustomUser"},
        {"model": "core.Post"},
    ],

    # === Ось ця частина робить магію "Reddit" ===
    "ui_tweaks": {
        "brand_colour": "#FF4500",      # Reddit Orange
        "accent": "#FF4500",
        "primary": "#FF4500",
        "secondary": "#343A40",
        "warning": "#FF4500",
        
        "navbar": "navbar-dark-primary", # Використовує primary колір
        "sidebar": "sidebar-dark-primary", # Використовує primary колір
        
        "navbar_small_text": False,
        "footer_small_text": False,
        "body_small_text": False,
        "brand_small_text": False,
        "sidebar_nav_small_text": False,
        "accent_colour": "#FF4500",
        "primary_colour": "#FF4500",
        "secondary_colour": "#343A40",
        "success_colour": "#28A745",
        "info_colour": "#17A2B8",
        "warning_colour": "#FF4500",
        "danger_colour": "#DC3545",
        "light_colour": "#F8F9FA",
        "dark_colour": "#343A40"
    },
    # === Кінець магії ===

    "icons": {
        "auth": "fas fa-users-cog",
        "users.CustomUser": "fas fa-user",
        "users.Profile": "fas fa-id-card",
        "core.Post": "fas fa-newspaper",
        "core.Category": "fas fa-tags",
        "core.Tag": "fas fa-hashtag",
        "core.PostComment": "fas fa-comments",
    },
    "default_icon_parents": "fas fa-chevron-circle-right",
    "default_icon_children": "fas fa-circle",
}

CKEDITOR_UPLOAD_PATH = "uploads/"
CKEDITOR_CONFIGS = {
    'default': {
        'toolbar': 'Custom',
        'toolbar_Custom': [
            ['Bold', 'Italic', 'Underline'],
            ['NumberedList', 'BulletedList', '-', 'Outdent', 'Indent', '-', 'JustifyLeft', 'JustifyCenter', 'JustifyRight', 'JustifyBlock'],
            ['Link', 'Unlink'],
            ['RemoveFormat', 'Source'],
            ['Image', 'Blockquote', 'Table']
        ],
        'skin': 'moono-dark', # Темна тема
        'width': '100%',
    },
}

# Application definition
INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_ckeditor_5',
    'users',
    'core',
]

# --- ВИПРАВЛЕНО: Відновлено обов'язковий список MIDDLEWARE ---
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'dlango_blog.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'core.context_processors.global_context', 
            ],
            'libraries': {
                'core_filters': 'core.templatetags.core_filters',
            }
        },
    },
]

WSGI_APPLICATION = 'dlango_blog.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'uk-ua'

TIME_ZONE = 'Europe/Kyiv'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']


STATIC_ROOT = BASE_DIR / 'staticfiles' 
STATICFILES_STORAGE = 'django.contrib.staticfiles.storage.StaticFilesStorage'

LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/login/'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = 'users.CustomUser'

# --- ДОДАНО ДЛЯ РОЗСИЛКИ В КОНСОЛЬ ---
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
DEFAULT_FROM_EMAIL = 'noreply@myblog.com'

SITE_URL = 'http://127.0.0.1:8000'

CKEDITOR_UPLOAD_PATH = "uploads/"
CKEDITOR_5_FILE_UPLOAD_PERMISSION = "authenticated"  # Дозволяє завантаження для авторизованих користувачів
CKEDITOR_5_CONFIGS = {
    'default': {
        'toolbar': ['heading', '|', 'bold', 'italic', 'link',
                    'bulletedList', 'numberedList', 'blockQuote', 'imageUpload'],
        'language': 'uk',
    },
    'extends': {
        'toolbar': ['heading', '|', 'bold', 'italic', 'link', 'underline', 'strikethrough',
                    'bulletedList', 'numberedList', 'blockQuote', 'imageUpload', 
                    '|', 'outdent', 'indent', '|', 'insertTable', 'mediaEmbed',
                    '|', 'undo', 'redo', '|', 'sourceEditing'],
        'language': 'uk',
        'image': {
            'toolbar': ['imageTextAlternative', 'imageStyle:alignLeft', 
                       'imageStyle:alignRight', 'imageStyle:alignCenter', 
                       'imageStyle:side'],
        },
        'table': {
            'contentToolbar': ['tableColumn', 'tableRow', 'mergeTableCells'],
        },
    },
}

